/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeadvert_browsercontrol */

#ifndef _Included_nativeadvert_browsercontrol
#define _Included_nativeadvert_browsercontrol
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     nativeadvert_browsercontrol
	 * Method:    resize0
	 * Signature: (II)V
	 */
	JNIEXPORT void JNICALL Java_nativeadvert_browsercontrol_resize0
	(JNIEnv *, jclass, jint, jint);

	/*
	 * Class:     nativeadvert_browsercontrol
	 * Method:    navigate0
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_nativeadvert_browsercontrol_navigate0
	(JNIEnv *, jclass, jstring);

	/*
	 * Class:     nativeadvert_browsercontrol
	 * Method:    browsercontrol0
	 * Signature: (Ljava/awt/Canvas;Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_nativeadvert_browsercontrol_browsercontrol0
	(JNIEnv *, jclass, jobject, jstring);

	/*
	 * Class:     nativeadvert_browsercontrol
	 * Method:    destroy0
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_nativeadvert_browsercontrol_destroy0
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
